-- Board 게시판
CREATE TABLE EDUBOARD(
	SEQ NUMBER,
	ID VARCHAR2(20) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(500) NOT NULL,
	DELFLAG CHAR(1) NOT NULL,
	CREATEAT DATE
);

CREATE TABLE EMPINFO 
	AS SELECT ID, PASSWORD, NAME, PHONE, ENABLE, AUTH
		FROM MEMBERINFO m ;
		
ALTER TABLE EDUBOARD ADD CONSTRAINT EDUBOARD_PK PRIMARY KEY (SEQ);
ALTER TABLE EMPINFO ADD CONSTRAINT EMPINFO_PK PRIMARY KEY (ID);
ALTER TABLE EDUBOARD ADD CONSTRAINT EDUBOARD_FK FOREIGN KEY(ID) REFERENCES EMPINFO (ID);

















