-- 전체 조회
SELECT SEQ, ID, TITLE , DELFLAG , TO_CHAR(CREATEAT, 'YYYY-MM-DD') CREATEAT , NAME
	FROM EDUBOARD e JOIN EMPINFO e2 
	USING(ID);

-- 페이징
SELECT SEQ,ID ,TITLE ,
	   CONTENT , CREATEAT, DELFLAG
	FROM (
		SELECT SEQ,ID ,TITLE ,
			   CONTENT , TO_CHAR(CREATEAT, 'YYYY-MM-DD') CREATEAT, DELFLAG ,
			   ROW_NUMBER() OVER(ORDER BY SEQ DESC) RN
			FROM EDUBOARD e )
	WHERE RN BETWEEN 1 AND 5;

-- 전체 글의 갯수
SELECT COUNT(*) 
	FROM EDUBOARD e ;

-- 상세 조회
SELECT SEQ, ID, TITLE , CONTENT , DELFLAG , TO_CHAR(CREATEAT, 'YYYY-MM-DD') CREATEAT , NAME
	FROM EDUBOARD e JOIN EMPINFO e2 
	USING(ID)
	WHERE SEQ = '1';

-- 입력
SELECT NVL(MAX(SEQ)+1,1)
	FROM EDUBOARD e ;

INSERT INTO EDUBOARD e (SEQ, ID, TITLE, CONTENT, 
						DELFLAG, CREATEAT)
	VALUES((SELECT NVL(MAX(SEQ)+1,1) FROM EDUBOARD e), 'HAPPY00', 'Query Test', 
			'Query Test Content', 'N', SYSDATE);
		
-- 수정
UPDATE EDUBOARD SET CONTENT = 'Query Update Test' WHERE SEQ = '1';

-- 삭제
UPDATE EDUBOARD SET DELFLAG  = 'Y' WHERE SEQ = '3';

-- 다중 삭제
UPDATE EDUBOARD SET DELFLAG  = 'Y' WHERE SEQ IN('1','2','3');

-- 로그인
SELECT ID, PASSWORD , NAME , ENABLE , AUTH 
	FROM EMPINFO e 
	WHERE ID = 'HAPPY00' AND PASSWORD = 'HAPPY00' AND ENABLE = 'Y';

-- 내 글 조회
SELECT SEQ,ID ,TITLE ,
	   CONTENT , CREATEAT, DELFLAG
	FROM (
		SELECT SEQ,ID ,TITLE ,
			   CONTENT , TO_CHAR(CREATEAT, 'YYYY-MM-DD') CREATEAT, DELFLAG ,
			   ROW_NUMBER() OVER(ORDER BY SEQ DESC) RN
			FROM EDUBOARD e )
	WHERE (RN BETWEEN 1 AND 5) AND ID = 'HAPPY00';

-- 내 글의 갯수
SELECT COUNT(*) 
	FROM EDUBOARD e 
	WHERE ID = 'HAPPY00' AND DELFLAG = 'N';

-- 중복 아이디 검사
SELECT ID
	FROM EMPINFO e 
	WHERE ID = 'TEST';

-- 회원 가입
INSERT INTO EMPINFO e (ID, PASSWORD, NAME, 
						PHONE, ENABLE, AUTH)
	VALUES ('TEST11123', 'TEST', 'TEST', '000', 'D', 'USER');

-- 회원 가입 파일 업로드
INSERT INTO EMPINFO e (ID, PASSWORD, NAME, 
						PHONE, ENABLE, AUTH, FILENAME)
	VALUES ('FILETEST', 'TEST', 'TEST', '000', 'D', 'USER', 'TEST');

-- 회원 가입 승인
UPDATE EMPINFO SET ENABLE = 'Y' WHERE ID = 'TEST';

-- 회원 삭제
UPDATE EMPINFO SET ENABLE = 'N' WHERE ID IN 'TEST';

-- 회원 목록 조회
SELECT ID, NAME , PHONE , ENABLE , AUTH , FILENAME
	FROM EMPINFO e 
	WHERE ENABLE = 'D';

-- 대기 회원 조회
SELECT ID , NAME, PHONE,
		ENABLE, AUTH, FILENAME
	FROM (
		SELECT ID, NAME , PHONE , 
				ENABLE , AUTH, FILENAME,
			   ROW_NUMBER() OVER(ORDER BY NAME DESC) RN
			FROM EMPINFO e	
			WHERE ENABLE = 'D')
	WHERE RN BETWEEN 1 AND 5 ;

-- 대기 회원 수
SELECT COUNT(*) 
	FROM EMPINFO e2
	WHERE ENABLE  = 'D';

-- 회원 목록 페이징
SELECT ID, NAME , PHONE ,
		ENABLE , AUTH , FILENAME
	FROM (
		SELECT  ID, NAME , PHONE , 
				ENABLE , AUTH, FILENAME,
			   ROW_NUMBER() OVER(ORDER BY ENABLE DESC) RN
			FROM EMPINFO e )
	WHERE RN BETWEEN 1 AND 5;

-- 회원 전체 수
SELECT COUNT(*) 
	FROM EMPINFO e ;


-- 파일 이름 저장 컬럼 추가
ALTER TABLE EMPINFO ADD FILENAME VARCHAR2(1000);


















